openapi: 3.0.3

info:
  title: Hockey API
  version: 1.0.0
  description: API documentation for the Hockey API

servers:
  - url: http://localhost:3000/api
    description: Local development server
  - url: https://final-project-hockey-api-service.onrender.com
    description: Production Server

tags:
  - name: Auth
    description: User authentification endpoints
  - name: Teams
    description: Operations related to teams
  - name: Lineups
    description: Operations related to lineups
  - name: Players
    description: Operations related to players

paths:
  /api/auth/signup:
    post:
      tags:
        - Auth
      summary: Sign up
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthCredentials'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  email:
                    type: string
        '400':
          $ref: '#/components/responses/InvalidUserInput'
        '409':
          description: Email already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
                example:
                  errors:
                    - "Email already exists"

  /api/auth/login:
    post:
      tags:
        - Auth
      summary: Log in
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthCredentials'
      responses:
        '200':
          description: Successful Login
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
        '400':
          $ref: '#/components/responses/InvalidUserInput'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/teams:
    get:
      tags:
        - Teams
      summary: Get all teams
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
        '401':
          $ref: '#/components/responses/Unauthorized'
    
    post:
      tags:
        - Teams
      summary: Create a new team
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '201':
          description: Team created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
        '400':
          description: Bad request due to invalid data
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
                example:
                  errors:
                    - 'Name is required'
        '401':
          $ref: '#/components/responses/Unauthorized'
        
  
  /api/teams/{id}:
    get:
      tags:
        - Teams
      summary: Get a team by id
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ResourceId'
      responses:
        '200':
          description: Team found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
        '404':
          $ref: '#/components/responses/NotFound'
        '403':
          $ref: '#/components/responses/Forbidden'
        '400':
          $ref: '#/components/responses/InvalidId'
        '401':
          $ref: '#/components/responses/Unauthorized'

    put:
      tags:
        - Teams
      summary: Update a team
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ResourceId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Team updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
        '404':
          $ref: '#/components/responses/NotFound'
        '403':
          $ref: '#/components/responses/Forbidden'
        '400':
          $ref: '#/components/responses/InvalidId'
        '401':
          $ref: '#/components/responses/Unauthorized'

    delete:
      tags:
        - Teams
      summary: Delete a team
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ResourceId'
      responses:
        '200':
          description: Team deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Team deleted
        '404':
          $ref: '#/components/responses/NotFound'
        '403':
          $ref: '#/components/responses/Forbidden'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '400':
          $ref: '#/components/responses/InvalidId'

  /api/players:
    get:
      tags:
        - Players
      summary: Get all players
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
        '401':
          $ref: '#/components/responses/Unauthorized'

    post:
      tags:
        - Players
      summary: Create a player
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - position
                - teamId
              properties:
                name:
                  type: string
                position:
                  type: string
                teamId:
                  type: integer
      responses:
        '201':
          description: Player created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Player'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
                example:
                  errors:
                    - 'Name is required'
                    - 'Position is required'
                    - 'Team ID is required'
                  
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
    
  /api/players/{id}:
    get:
      tags:
        - Players
      summary: Get a player by Id
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ResourceId'
      responses:
        '200':
          description: Player found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Player'
        '404':
          $ref: '#/components/responses/NotFound'
        '403':
          $ref: '#/components/responses/Forbidden'
        '400':
          $ref: '#/components/responses/InvalidId'
        '401':
          $ref: '#/components/responses/Unauthorized'

    put:
      tags:
        - Players
      summary: Update a player
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ResourceId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                position:
                  type: string
      responses:
        '200':
          description: Player updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Player'
        '404':
          $ref: '#/components/responses/NotFound'
        '403':
          $ref: '#/components/responses/Forbidden'
        '400':
          $ref: '#/components/responses/InvalidId'
        '401':
          $ref: '#/components/responses/Unauthorized'

    delete:
      tags:
        - Players
      summary: Delete a player
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ResourceId'
      responses:
        '200':
          description: Player deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Player deleted successfully
        '404':
          $ref: '#/components/responses/NotFound'
        '403':
          $ref: '#/components/responses/Forbidden'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '400':
          $ref: '#/components/responses/InvalidId'

  /api/lineups:
    get:
      tags:
        - Lineups
      summary: Get all lineups
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of lineups
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Lineup'
        '401':
          $ref: '#/components/responses/Unauthorized'

    post:
      tags:
        - Lineups
      summary: Create a lineup
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - teamId
              properties:
                name:
                  type: string
                teamId:
                  type: integer
      responses:
        '201':
          description: Lineup created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lineup'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
                example:
                  errors:
                    - 'Name is required'
                    - 'Team ID is required'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'

  /api/lineups/{id}:
    get:
      tags:
        - Lineups
      summary: Get a lineup by ID
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ResourceId'
      responses:
        '200':
          description: Lineup found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lineup'
        '400':
          $ref: '#/components/responses/InvalidId'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      tags:
        - Lineups
      summary: Update a lineup
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ResourceId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Lineup updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lineup'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
                example:
                  errors:
                    - 'Name is required'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      tags:
        - Lineups
      summary: Delete a lineup
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ResourceId'
      responses:
        '200':
          description: Lineup deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Lineup deleted successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '400':
          $ref: '#/components/responses/InvalidId'

  /api/lineups/{id}/players:
    post:
      tags:
        - Lineups
      summary: Add a player to a lineup
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ResourceId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - playerId
              properties:
                playerId:
                  type: integer
      responses:
        '200':
          description: Player added to lineup
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Player successfully added to lineup
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: playerId and lineupId are required
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/lineups/{id}/players/{playerId}:
    delete:
      tags:
        - Lineups
      summary: Delete a player from a lineup
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ResourceId'
        - name: playerId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Player deleted from lineup
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Player successfully deleted from lineup
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '400':
          $ref: '#/components/responses/InvalidId'
      
      
components:
  schemas:
    Team:
      type: object 
      properties:
        id:
          type: integer
          readOnly: true
          example: 1
        name:
          type: string
          example: "Team Name"
        userId:
          type: integer
          readOnly: true
          example: 1
    
    Player:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
          example: 1
        name:
          type: string
          example: "John Smith"
        position:
          type: string
          example: "Forward"
        teamId:
          type: integer
          example: 1

    Lineup:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
          example: 1
        name:
          type: string
          example: "Starting lineup"
        teamId:
          type: integer
          example: 1
        players:
          type: array
          items:
            $ref: '#/components/schemas/Player'

    AuthCredentials:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: 'user@example.com'
        password: 'password123'

  parameters:
    ResourceId:
      name: id
      in: path
      required: true
      description: Resource ID
      schema:
        type: integer
        example: 1

  responses:
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
            example:
              error: "Resource not found"

    InvalidUserInput:
      description: Bad request due to invalid data
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: array
                items:
                  type: string
            example:
              errors:
                - 'Email is required'
                - 'Password is required'
    
    InvalidId:
      description: Invalid ID
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: array
                items:
                  type: string
            example:
              errors: ['ID must be a positive integer']

    Unauthorized:
      description: Client is not authenticated
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
            example:
              error: "Not authenticated. Please provide a valid token."

    Forbidden:
      description: Client is not authorized
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
            example:
              error: "Forbidden: insufficient permission"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT